#!/bin/bash
TOKEN="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbWc5cnZ5NzMwMDAxeWI1NDUwamg5azYyIiwiaWQiOiJjbWc5c
nZ5NzMwMDAxeWI1NDUwamg5azYyIiwicm9sZSI6IkFETUlOIiwiZW1haWwiOiJhZG1pbkBtYXNhaXNjaG9vbC5jb20iLCJuYW1lIjoiYWRta
W4iLCJhc3NpZ25lZEFkbWluSWQiOm51bGwsImlhdCI6MTc1OTQzNTM1MiwiZXhwIjoxNzU5NDY0MTUyfQ.pbFvr56jJ-AaIveYYEi6-cMak4
aJN22wxKJeBJoAPkY"

curl -H "Authorization: Bearer $TOKEN" http://localhost:4000/api/admin/users
